Update jq curriculum
gizumo-inc/jquery_curriculum_new pull request #1
Opened 2021-07-29 07:41 UTC by takumisakaino

## タスクのリンク
- https://www.notion.so/3-_js-94c95bdad1114ce39a06015668d57a94
- https://www.notion.so/_-e4ecc8b746824fe7a70eab76dad203da

## やったこと
- 6~9の削除
- q4,q5は関数化させることの追記
- q5はeachの引数の説明の追加
- q1の2問目のanswerの色変更
- q1(hover,fadeout,eq)の問題はのちに回収できるので削除

2021-08-02 09:17 UTC, kanemototomoki requested changes

2021-08-02 09:17 UTC, kanemototomoki commented on work/sixth/index.html
> +        <div class="message"></div>
https://github.com/gizumo-inc/gizumo-inc.github.io/pull/11#discussion_r680807449

2021-08-02 09:17 UTC, kanemototomoki commented on work/sixth/index.html
> +      // $.each(配列, function functionName() {}) 配列に対しての繰り返し処理が行えます。
[nits]
`each()` の説明は前の問題でしているから必要ないかもしれません！

2021-08-03 09:28 UTC, takumisakaino commented on work/sixth/index.html
> +      // $.each(配列, function functionName() {}) 配列に対しての繰り返し処理が行えます。
q5は$(DOM).each(function(){});で
q6は$.each(配列, function(){});なので
両方紹介してるサイトも多いですし、個人的には残すのありかなって思ってます！

2021-09-02 02:33 UTC, merged